-- drop the statistics table and create the schema for the table
DROP TABLE IF EXISTS statistics CASCADE;
CREATE TABLE statistics (
    id          int GENERATED BY DEFAULT AS IDENTITY, -- automatically generate id value
    timestamp   timestamp NOT NULL,
    total       float NOT NULL,
    PRIMARY KEY (id)
);

-- drop the users table and create the schema for the table
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    id              int GENERATED BY DEFAULT AS IDENTITY, -- automatically generate id value
    username        varchar(32) NOT NULL UNIQUE, -- email for oauth accounts
    password        varchar(128), -- null if oauth account
    role            varchar(32) NOT NULL,
    hourly_salary   float NOT NULL,
    hours           float NOT NULL,
    PRIMARY KEY (id)
);

-- drop the inventory table and create the schema for the table
DROP TABLE IF EXISTS inventory CASCADE;
CREATE TABLE inventory (
    id          int GENERATED BY DEFAULT AS IDENTITY, -- automatically generate id value
    name        varchar(255) NOT NULL,
    avg_cost    float NOT NULL,
    qty         float NOT NULL,
    min_qty     float NOT NULL,
    max_qty     float NOT NULL,
    PRIMARY KEY (id)
);

-- drop the menu_items table and create the schema for the table
DROP TABLE IF EXISTS menu_items CASCADE;
CREATE TABLE menu_items (
    id          int GENERATED BY DEFAULT AS IDENTITY, -- automatically generate id value
    name        varchar(255) NOT NULL,
    type        varchar(255) NOT NULL,
    price       float NOT NULL,
    net_price   float,
    popularity  float,
    description varchar(511) NOT NULL,
    image       bytea, -- nullable to allow items with no image
    weather     varchar(255),
    PRIMARY KEY (id)
);

-- drop the orders table and create the schema for the table
DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
    id          int GENERATED BY DEFAULT AS IDENTITY, -- automatically generate id value
    stat_id     int DEFAULT NULL,
    timestamp   timestamp NOT NULL,
    discount    float NOT NULL,
    total       float NOT NULL,
    status      varchar(31) NOT NULL, -- FILLED | PENDING | CANCELED
    PRIMARY KEY (id),
    CONSTRAINT  fk_stat
        FOREIGN KEY (stat_id)
            REFERENCES  statistics(id) ON DELETE CASCADE
);

--------------------------------------------
--------------------------------------------
--             JUNCTION TABLES            --
--------------------------------------------
--------------------------------------------

-- drop the ingredients table and create the schema for the table
DROP TABLE IF EXISTS ingredients CASCADE;
CREATE TABLE ingredients (
    item_id         int NOT NULL,
    inventory_id    int NOT NULL,
    amount          float NOT NULL,
    CONSTRAINT  fk_item
        FOREIGN KEY (item_id)
            REFERENCES  menu_items(id) ON DELETE CASCADE,
    CONSTRAINT  fk_inventory
        FOREIGN KEY (inventory_id)
            REFERENCES  inventory(id) ON DELETE CASCADE
);

-- drop the order_items table and create the schema for the table
DROP TABLE IF EXISTS order_items CASCADE;
CREATE TABLE order_items (
    order_id        int NOT NULL,
    item_id         int NOT NULL,
    qty             int NOT NULL,
    CONSTRAINT  fk_order
        FOREIGN KEY (order_id)
            REFERENCES  orders(id) ON DELETE CASCADE,
    CONSTRAINT  fk_item
        FOREIGN KEY (item_id)
            REFERENCES  menu_items(id) ON DELETE CASCADE
);

-- drop the cumulative_items table and create the schema for the table
DROP TABLE IF EXISTS cumulative_items CASCADE;
CREATE TABLE cumulative_items (
    stat_id         int NOT NULL,
    item_id         int NOT NULL,
    qty             int NOT NULL,
    CONSTRAINT  fk_stat
        FOREIGN KEY (stat_id)
            REFERENCES  statistics(id) ON DELETE CASCADE,
    CONSTRAINT  fk_item
        FOREIGN KEY (item_id)
            REFERENCES  menu_items(id) ON DELETE CASCADE
);

-- drop the salary table and create the schema for the table
DROP TABLE IF EXISTS salary CASCADE;
CREATE TABLE salary (
    stat_id         int NOT NULL,
    user_id         int NOT NULL,
    payroll_total   int NOT NULL,
    CONSTRAINT  fk_stat
        FOREIGN KEY (stat_id)
            REFERENCES  statistics(id) ON DELETE CASCADE,
    CONSTRAINT  fk_user
        FOREIGN KEY (user_id)
            REFERENCES  users(id) ON DELETE CASCADE
);

--------------------------------------------
--------------------------------------------
--             SUB TABLES            --
--------------------------------------------
--------------------------------------------
-- drop the seasonal_items table and create the schema for the table
DROP TABLE IF EXISTS seasonal_items CASCADE;
CREATE TABLE seasonal_items (
    item_id         int NOT NULL, -- automatically generate id value
    start_date      timestamp DEFAULT NULL,
    end_date        timestamp DEFAULT NULL,
    recurring       bool DEFAULT NULL,
    CONSTRAINT  fk_item
        FOREIGN KEY (item_id)
            REFERENCES  menu_items(id) ON DELETE CASCADE
);

