// DONE

import type { Metadata } from 'next';
import './globals.css';

import { Poppins, Roboto_Mono } from 'next/font/google';

const poppins = Poppins({
    weight: ['400', '700'],
    style: ['normal'],
    subsets: ['latin'],
    variable: '--font-poppins',
    display: 'swap',
});

const robotoMono = Roboto_Mono({
    subsets: ['latin'],
    variable: '--font-roboto-mono',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Rev's American Grill",
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${poppins.variable} ${robotoMono.variable}`}
        >
            <head>
                <link rel="icon" href="/RLogo.ico" />
            </head>
            <body>{children}</body>
        </html>
    );
}
